"""Build the reproducible public Blender add-on ZIP file."""

import hashlib
import re
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "seele_blender"
DIST = ROOT / "dist"
FIXED_TIME = (2026, 8, 8, 0, 0, 0)

BUILD_CHANNEL = "public"
BUILD_LABEL = "Public Release"
PRODUCTION_ORIGIN = "https://www.seeles.ai"

DOWNLOAD_HOSTS = (
    "static.seeles.ai",
    "agent-workspace-1368252780.cos.na-ashburn.myqcloud.com",
)


def addon_version():
    source = (PACKAGE / "__init__.py").read_text(encoding="utf-8")
    match = re.search(r'"version"\s*:\s*\((\d+),\s*(\d+),\s*(\d+)\)', source)
    if not match:
        raise RuntimeError("Unable to read add-on version")
    return ".".join(match.groups())


def render_config():
    hosts = "\n".join(f'    "{host}",' for host in DOWNLOAD_HOSTS)
    return (
        '"""Generated build-time service configuration."""\n\n'
        f'BUILD_CHANNEL = "{BUILD_CHANNEL}"\n'
        f'BUILD_LABEL = "{BUILD_LABEL}"\n\n'
        f'DEFAULT_PRODUCTION_ORIGIN = "{PRODUCTION_ORIGIN}"\n\n'
        'DEFAULT_DOWNLOAD_HOSTS = (\n'
        f'{hosts}\n'
        ')\n\n'
        'DEFAULT_BRIDGE_PORT = 9878\n'
    ).encode("utf-8")


def _write_entry(archive, name, content):
    info = zipfile.ZipInfo(name, date_time=FIXED_TIME)
    info.compress_type = zipfile.ZIP_DEFLATED
    info.external_attr = 0o644 << 16
    archive.writestr(info, content)


def build():
    version = addon_version()
    output = DIST / f"seele-blender-{version}-public.zip"
    DIST.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output, "w") as archive:
        for path in sorted(PACKAGE.rglob("*")):
            if not path.is_file() or "__pycache__" in path.parts or path.suffix in {".pyc", ".pyo"}:
                continue
            relative = path.relative_to(PACKAGE).as_posix()
            content = render_config() if relative == "release_config.py" else path.read_bytes()
            _write_entry(archive, f"seele_blender/{relative}", content)
        _write_entry(archive, "seele_blender/LICENSE.txt", (ROOT / "LICENSE").read_bytes())
    validate_archive(output)
    digest = hashlib.sha256(output.read_bytes()).hexdigest().upper()
    return output, digest


def validate_archive(output):
    with zipfile.ZipFile(output) as archive:
        names = archive.namelist()
        if any("__pycache__" in name or name.endswith((".pyc", ".pyo")) for name in names):
            raise RuntimeError(f"Generated bytecode found in {output.name}")
        config = archive.read("seele_blender/release_config.py").decode("utf-8")
        preferences = archive.read("seele_blender/preferences.py").decode("utf-8")
    if f'BUILD_CHANNEL = "{BUILD_CHANNEL}"' not in config:
        raise RuntimeError(f"Wrong build channel in {output.name}")
    if PRODUCTION_ORIGIN not in config:
        raise RuntimeError(f"Missing production Origin in {output.name}")
    for host in DOWNLOAD_HOSTS:
        if host not in config:
            raise RuntimeError(f"Missing download host in {output.name}: {host}")
    editable_markers = ("port: IntProperty", "production_origin: StringProperty", "download_hosts: StringProperty", "legacy_enabled: BoolProperty")
    if any(marker in preferences for marker in editable_markers):
        raise RuntimeError(f"Editable service configuration found in {output.name}")
def main():
    output, digest = build()
    print(f"{output.name}  SHA256={digest}")


if __name__ == "__main__":
    main()
